=== Shopify/theme-liquid-docs/schemas/theme/section.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Shopify Liquid Theme Section Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name attribute determines the section title that is shown in the theme editor.",
      "markdownDescription": "The `name` attribute determines the section title that is shown in the theme editor.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#name)"
    },

    "tag": {
      "type": "string",
      "description": "The HTML element that is used to wrap the section.",
      "markdownDescription": "The HTML element that is used to wrap the section.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#tag)",
      "enum": ["article", "aside", "div", "footer", "header", "section"]
    },

    "class": {
      "type": "string",
      "description": "Additional CSS class for the section.",
      "markdownDescription": "Additional CSS class for the section.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#class)"
    },

    "limit": {
      "type": "integer",
      "description": "The number of times a section can be added to a template or section group.",
      "markdownDescription": "The number of times a section can be added to a template or section group.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#limit)",
      "minimum": 1,
      "maximum": 2
    },

    "settings": {
      "$ref": "./strict_settings.json"
    },

    "max_blocks": {
      "type": "integer",
      "description": "There's a limit of 50 blocks per section. You can specify a lower limit with the max_blocks attribute",
      "markdownDescription": "There's a limit of 50 blocks per section. You can specify a lower limit with the `max_blocks` attribute.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#max_blocks)",
      "minimum": 1,
      "maximum": 50
    },

    "blocks": {
      "type": "array",
      "description": "Blocks are reusable modules of content that can be added, removed, and reordered within a section.",
      "markdownDescription": "Blocks are reusable modules of content that can be added, removed, and reordered within a section.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#blocks)",
      "properties": {
        "type": {
          "description": "The block type. Can be one of the following values: @theme, @app, or a custom block type.",
          "markdownDescription": "The block type. Can be one of the following values: @theme, @app, or a custom block type.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#blocks)"
        }
      },
      "items": {
        "type": "object",
        "required": ["type"],
        "properties": {
          "type": {
            "type": "string",
            "description": "The type of block that can be added to this block.",
            "markdownDescription": "The type of block that can be added to this block.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/blocks/theme-blocks/schema#blocks)"
          }
        },
        "$comment": "The allOf rule here exists because that's how we do discriminated unions in JSON schemas. If a rule matches, that rule will be used to document the type property. Otherwise we fallback to the docs above.",
        "allOf": [
          {
            "if": { "required": ["type"], "properties": { "type": { "const": "@theme" } } },
            "then": { "$ref": "./theme_block_entry.json" }
          },
          {
            "if": { "required": ["type"], "properties": { "type": { "const": "@app" } } },
            "then": { "$ref": "./app_block_entry.json" }
          },
          {
            "if": {
              "required": ["type"],
              "properties": {
                "type": {
                  "type": "string",
                  "not": { "enum": ["@app", "@theme"] }
                }
              }
            },
            "then": {
              "oneOf": [
                { "$ref": "./targetted_block_entry.json" },
                { "$ref": "./local_block_entry.json" }
              ]
            }
          }
        ]
      }
    },

    "presets": {
      "type": "array",
      "description": "Presets are default configurations of sections that enable users to easily add a section to a JSON template through the theme editor.",
      "markdownDescription": "Presets are default configurations of sections that enable users to easily add a section to a [JSON template](https://shopify.dev/docs/themes/architecture/templates/json-templates) through the theme editor.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#presets)",
      "items": {
        "$ref": "./preset.json"
      }
    },

    "default": {
      "type": "object",
      "description": "Default configuration for statically rendered sections.",
      "markdownDescription": "Default configuration for statically rendered sections.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#default)",
      "properties": {
        "settings": {
          "$ref": "./default_setting_values.json"
        },
        "blocks": {
          "type": "array",
          "description": "Default blocks configurations to ship with this default.",
          "markdownDescription": "Default blocks configurations to ship with this default.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#default)",
          "items": {
            "type": "object",
            "required": ["type"],
            "properties": {
              "type": {
                "type": "string",
                "description": "The block type."
              },
              "settings": {
                "$ref": "./default_setting_values.json"
              }
            }
          }
        }
      }
    },

    "locales": {
      "type": "object",
      "description": "Sections can provide their own set of translated strings through the locales object. This is separate from the locales directory of the theme, which makes it a useful feature for sections that are meant to be installed on multiple themes or shops.",
      "markdownDescription": "Sections can provide their own set of translated strings through the `locales` object. This is separate from the `locales` directory of the theme, which makes it a useful feature for sections that are meant to be installed on multiple themes or shops.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#locales)",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      }
    },

    "enabled_on": {
      "description": "Restrict the section to certain template page types and section group types.",
      "markdownDescription": "Restrict the section to certain template page types and section group types.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#enabled_on)",
      "$ref": "#/definitions/sectionToggle"
    },

    "disabled_on": {
      "description": "Prevent the section from being used on certain template page types and section group types.",
      "markdownDescription": "Prevent the section from being used on certain template page types and section group types.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/sections/section-schema#disabled_on)",
      "$ref": "#/definitions/sectionToggle"
    }
  },

  "definitions": {
    "sectionToggle": {
      "type": "object",
      "description": "Restrict the section to certain template page types and section group types.",
      "additionalProperties": false,
      "properties": {
        "templates": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "*",
              "404",
              "article",
              "blog",
              "captcha",
              "cart",
              "collection",
              "customers/account",
              "customers/activate_account",
              "customers/addresses",
              "customers/login",
              "customers/order",
              "customers/register",
              "customers/reset_password",
              "gift_card",
              "index",
              "list-collections",
              "metaobject",
              "page",
              "password",
              "policy",
              "product",
              "search"
            ]
          },
          "uniqueItems": true
        },
        "groups": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        }
      }
    }
  }
}

=== Shopify/theme-liquid-docs/tests/fixtures/section-schema-preset-blocks-as-hash.json
{
    "name": "Example Section",
    "tag": "div",
    "class": "example-class",
    "limit": 1,
    "settings": [],
    "max_blocks": 2,
    "blocks": [],
    "presets": [
      {
        "name": "Example Preset",
        "settings": {
        },
        "blocks": {
          "exampleBlock": {
            "type": "text",
            "settings": {}
          },
          "exampleBlock2": {
            "type": "text",
            "static": true,
            "settings": {},
            "blocks": {
              "nestedExampleBlock": {
                "type": "text"
              }
            }
          }
        },
        "block_order": [
          "exampleBlock",
          "exampleBlock2"
        ]
      }
    ],
    "locales": {
      "en": {
        "exampleString": "This is a string"
      }
    },
    "enabled_on": {
      "templates": [
        "index"
      ],
      "groups": [
        "exampleGroup"
      ]
    },
    "disabled_on": {
      "templates": [
        "product"
      ],
      "groups": [
        "exampleGroup2"
      ]
    }
  }

=== Shopify/theme-liquid-docs/tests/fixtures/section-schema-1.json
{
  "name": "t:sections.announcement-bar.name",
  "max_blocks": 12,
  "class": "announcement-bar-section",
  "enabled_on": {
    "groups": ["*", "header"]
  },
  "settings": [
    {
      "type": "color_scheme",
      "id": "color_scheme",
      "label": "t:sections.all.colors.label",
      "default": "accent-1"
    },
    {
      "type": "checkbox",
      "id": "show_line_separator",
      "default": true,
      "label": "t:sections.header.settings.show_line_separator.label"
    },
    {
      "type": "header",
      "content": "t:sections.announcement-bar.settings.header__1.content",
      "info": "t:sections.announcement-bar.settings.header__1.info"
    },
    {
      "type": "checkbox",
      "id": "show_social",
      "default": false,
      "label": "t:sections.announcement-bar.settings.show_social.label"
    },
    {
      "type": "header",
      "content": "t:sections.announcement-bar.settings.header__2.content"
    },
    {
      "type": "checkbox",
      "id": "auto_rotate",
      "label": "t:sections.announcement-bar.settings.auto_rotate.label",
      "default": false
    },
    {
      "type": "range",
      "id": "change_slides_speed",
      "min": 5,
      "max": 10,
      "step": 1,
      "unit": "s",
      "label": "t:sections.announcement-bar.settings.change_slides_speed.label",
      "default": 5
    }
  ],
  "blocks": [
    {
      "type": "announcement",
      "name": "t:sections.announcement-bar.blocks.announcement.name",
      "settings": [
        {
          "type": "text",
          "id": "text",
          "default": "Welcome to our store",
          "label": "t:sections.announcement-bar.blocks.announcement.settings.text.label"
        },
        {
          "type": "url",
          "id": "link",
          "label": "t:sections.announcement-bar.blocks.announcement.settings.link.label"
        }
      ]
    }
  ],
  "presets": [
    {
      "name": "t:sections.announcement-bar.presets.name",
      "blocks": [
        {
          "type": "announcement"
        }
      ]
    }
  ]
}

=== Shopify/theme-liquid-docs/tests/fixtures/section-schema-static-block-preset.json
{
  "name": "Example Section",
  "tag": "div",
  "class": "example-class",
  "limit": 1,
  "settings": [],
  "max_blocks": 2,
  "blocks": [],
  "presets": [
    {
      "name": "Example Preset 1",
      "settings": {
      },
      "blocks": [
        {
          "type": "exampleBlock",
          "static": false,
          "blocks": {
            "exampleBlock": {
              "type": "exampleBlock",
              "static": true,
              "settings": {}
            }
          },
          "settings": {}
        }
      ]
    },
    {
      "name": "Example Preset 2",
      "settings": {
      },
      "blocks": [
        {
          "type": "exampleBlock",
          "static": true,
          "settings": {}
        }
      ]
    },
    {
      "name": "Example Preset 3",
      "settings": {
      },
      "blocks": [
        {
          "type": "exampleBlock",
          "static": true,
          "id": "blockId",
          "settings": {}
        }
      ]
    }
  ],
  "locales": {
    "en": {
      "exampleString": "This is a string"
    }
  },
  "enabled_on": {
    "templates": [
      "index"
    ],
    "groups": [
      "exampleGroup"
    ]
  },
  "disabled_on": {
    "templates": [
      "product"
    ],
    "groups": [
      "exampleGroup2"
    ]
  }
}

=== Shopify/theme-liquid-docs/test/fixtures/section-schema-6.json
{
  "name": "Example Section",
  "tag": "div",
  "class": "example-class",
  "limit": 1,
  "settings": [],
  "max_blocks": 2,
  "blocks": [],
  "presets": [
    {
      "name": "Example Preset",
      "settings": {
        "exampleString": "This is a string",
        "exampleNumber": 123,
        "exampleBoolean": true,
        "exampleArray": ["String 1", "String 2"]
      },
      "blocks": [
        {
          "type": "exampleBlock",
          "settings": {
            "exampleString": "This is a string",
            "exampleNumber": 123,
            "exampleBoolean": true,
            "exampleArray": ["String 1", "String 2"]
          }
        }
      ]
    }
  ],
  "default": {
    "settings": {
      "exampleString": "This is a string",
      "exampleNumber": 123,
      "exampleBoolean": true,
      "exampleArray": ["String 1", "String 2"]
    },
    "blocks": [
      {
        "type": "exampleBlock",
        "settings": {
          "exampleString": "This is a string",
          "exampleNumber": 123,
          "exampleBoolean": true,
          "exampleArray": ["String 1", "String 2"]
        }
      }
    ]
  },
  "locales": {
    "en": {
      "exampleString": "This is a string"
    }
  },
  "enabled_on": {
    "templates": ["index"],
    "groups": ["exampleGroup"]
  },
  "disabled_on": {
    "templates": ["product"],
    "groups": ["exampleGroup2"]
  }
}

=== Shopify/theme-liquid-docs/tests/fixtures/section-schema-4.json
{
  "name": "t:sections.slideshow.name",
  "tag": "section",
  "class": "section",
  "disabled_on": {
    "groups": ["header", "footer"]
  },
  "settings": [
    {
      "type": "select",
      "id": "layout",
      "options": [
        {
          "value": "full_bleed",
          "label": "t:sections.slideshow.settings.layout.options__1.label"
        },
        {
          "value": "grid",
          "label": "t:sections.slideshow.settings.layout.options__2.label"
        }
      ],
      "default": "full_bleed",
      "label": "t:sections.slideshow.settings.layout.label"
    },
    {
      "type": "select",
      "id": "slide_height",
      "options": [
        {
          "value": "adapt_image",
          "label": "t:sections.slideshow.settings.slide_height.options__1.label"
        },
        {
          "value": "small",
          "label": "t:sections.slideshow.settings.slide_height.options__2.label"
        },
        {
          "value": "medium",
          "label": "t:sections.slideshow.settings.slide_height.options__3.label"
        },
        {
          "value": "large",
          "label": "t:sections.slideshow.settings.slide_height.options__4.label"
        }
      ],
      "default": "medium",
      "label": "t:sections.slideshow.settings.slide_height.label"
    },
    {
      "type": "select",
      "id": "slider_visual",
      "options": [
        {
          "value": "dots",
          "label": "t:sections.slideshow.settings.slider_visual.options__2.label"
        },
        {
          "value": "counter",
          "label": "t:sections.slideshow.settings.slider_visual.options__1.label"
        },
        {
          "value": "numbers",
          "label": "t:sections.slideshow.settings.slider_visual.options__3.label"
        }
      ],
      "default": "counter",
      "label": "t:sections.slideshow.settings.slider_visual.label"
    },
    {
      "type": "checkbox",
      "id": "auto_rotate",
      "label": "t:sections.slideshow.settings.auto_rotate.label",
      "default": false
    },
    {
      "type": "range",
      "id": "change_slides_speed",
      "min": 3,
      "max": 9,
      "step": 2,
      "unit": "s",
      "label": "t:sections.slideshow.settings.change_slides_speed.label",
      "default": 5
    },
    {
      "type": "header",
      "content": "t:sections.all.animation.content"
    },
    {
      "type": "select",
      "id": "image_behavior",
      "options": [
        {
          "value": "none",
          "label": "t:sections.all.animation.image_behavior.options__1.label"
        },
        {
          "value": "ambient",
          "label": "t:sections.all.animation.image_behavior.options__2.label"
        }
      ],
      "default": "none",
      "label": "t:sections.all.animation.image_behavior.label"
    },
    {
      "type": "header",
      "content": "t:sections.slideshow.settings.mobile.content"
    },
    {
      "type": "checkbox",
      "id": "show_text_below",
      "label": "t:sections.slideshow.settings.show_text_below.label",
      "default": true
    },
    {
      "type": "header",
      "content": "t:sections.slideshow.settings.accessibility.content"
    },
    {
      "type": "text",
      "id": "accessibility_info",
      "label": "t:sections.slideshow.settings.accessibility.label",
      "info": "t:sections.slideshow.settings.accessibility.info",
      "default": "Slideshow about our brand"
    }
  ],
  "blocks": [
    {
      "type": "slide",
      "name": "t:sections.slideshow.blocks.slide.name",
      "limit": 5,
      "settings": [
        {
          "type": "image_picker",
          "id": "image",
          "label": "t:sections.slideshow.blocks.slide.settings.image.label"
        },
        {
          "type": "inline_richtext",
          "id": "heading",
          "default": "Image slide",
          "label": "t:sections.slideshow.blocks.slide.settings.heading.label"
        },
        {
          "type": "select",
          "id": "heading_size",
          "options": [
            {
              "value": "h2",
              "label": "t:sections.all.heading_size.options__1.label"
            },
            {
              "value": "h1",
              "label": "t:sections.all.heading_size.options__2.label"
            },
            {
              "value": "h0",
              "label": "t:sections.all.heading_size.options__3.label"
            }
          ],
          "default": "h1",
          "label": "t:sections.all.heading_size.label"
        },
        {
          "type": "inline_richtext",
          "id": "subheading",
          "default": "Tell your brand's story through images",
          "label": "t:sections.slideshow.blocks.slide.settings.subheading.label"
        },
        {
          "type": "text",
          "id": "button_label",
          "default": "Button label",
          "label": "t:sections.slideshow.blocks.slide.settings.button_label.label",
          "info": "t:sections.slideshow.blocks.slide.settings.button_label.info"
        },
        {
          "type": "url",
          "id": "link",
          "label": "t:sections.slideshow.blocks.slide.settings.link.label"
        },
        {
          "type": "checkbox",
          "id": "button_style_secondary",
          "label": "t:sections.slideshow.blocks.slide.settings.secondary_style.label",
          "default": false
        },
        {
          "type": "select",
          "id": "box_align",
          "options": [
            {
              "value": "top-left",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__1.label"
            },
            {
              "value": "top-center",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__2.label"
            },
            {
              "value": "top-right",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__3.label"
            },
            {
              "value": "middle-left",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__4.label"
            },
            {
              "value": "middle-center",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__5.label"
            },
            {
              "value": "middle-right",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__6.label"
            },
            {
              "value": "bottom-left",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__7.label"
            },
            {
              "value": "bottom-center",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__8.label"
            },
            {
              "value": "bottom-right",
              "label": "t:sections.slideshow.blocks.slide.settings.box_align.options__9.label"
            }
          ],
          "default": "middle-center",
          "label": "t:sections.slideshow.blocks.slide.settings.box_align.label",
          "info": "t:sections.slideshow.blocks.slide.settings.box_align.info"
        },
        {
          "type": "checkbox",
          "id": "show_text_box",
          "label": "t:sections.slideshow.blocks.slide.settings.show_text_box.label",
          "default": true
        },
        {
          "type": "select",
          "id": "text_alignment",
          "options": [
            {
              "value": "left",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment.option_1.label"
            },
            {
              "value": "center",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment.option_2.label"
            },
            {
              "value": "right",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment.option_3.label"
            }
          ],
          "default": "center",
          "label": "t:sections.slideshow.blocks.slide.settings.text_alignment.label"
        },
        {
          "type": "range",
          "id": "image_overlay_opacity",
          "min": 0,
          "max": 100,
          "step": 10,
          "unit": "%",
          "label": "t:sections.slideshow.blocks.slide.settings.image_overlay_opacity.label",
          "default": 0
        },
        {
          "type": "color_scheme",
          "id": "color_scheme",
          "label": "t:sections.all.colors.label",
          "default": "background-1"
        },
        {
          "type": "header",
          "content": "t:sections.slideshow.settings.mobile.content"
        },
        {
          "type": "select",
          "id": "text_alignment_mobile",
          "options": [
            {
              "value": "left",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment_mobile.options__1.label"
            },
            {
              "value": "center",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment_mobile.options__2.label"
            },
            {
              "value": "right",
              "label": "t:sections.slideshow.blocks.slide.settings.text_alignment_mobile.options__3.label"
            }
          ],
          "default": "center",
          "label": "t:sections.slideshow.blocks.slide.settings.text_alignment_mobile.label"
        }
      ]
    }
  ],
  "presets": [
    {
      "name": "t:sections.slideshow.presets.name",
      "blocks": [
        {
          "type": "slide"
        },
        {
          "type": "slide"
        }
      ]
    }
  ]
}
