=== Shopify/theme-liquid-docs/schemas/theme/theme_block.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Shopify Liquid Theme Block Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name attribute determines the block title that's shown in the theme editor.",
      "markdownDescription": "The `name` attribute determines the block title that's shown in the theme editor.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/blocks/theme-blocks/schema#name)"
    },

    "settings": {
      "$ref": "./strict_settings.json"
    },

    "blocks": {
      "type": "array",
      "description": "Theme blocks can accept other app and theme blocks as children using the blocks attribute of their schema.",
      "markdownDescription": "Theme blocks can accept other app and theme blocks as children using the `blocks` attribute of their schema.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/blocks/theme-blocks/schema#blocks)",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["type"],
        "properties": {
          "type": {
            "type": "string",
            "description": "The type of block that can be added to this block.",
            "markdownDescription": "The type of block that can be added to this block.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/blocks/theme-blocks/schema#blocks)"
          }
        },
        "$comment": "The allOf rule here exists because that's how we do discriminated unions in JSON schemas. If a rule matches, that rule will be used to document the type property. Otherwise we fallback to the docs above.",
        "allOf": [
          {
            "if": { "required": ["type"], "properties": { "type": { "const": "@theme" } } },
            "then": { "$ref": "./theme_block_entry.json" }
          },
          {
            "if": { "required": ["type"], "properties": { "type": { "const": "@app" } } },
            "then": { "$ref": "./app_block_entry.json" }
          },
          {
            "if": {
              "required": ["type"],
              "properties": {
                "type": {
                  "type": "string",
                  "not": { "enum": ["@app", "@theme"] }
                }
              }
            },
            "then": { "$ref": "./targetted_block_entry.json" }
          }
        ]
      }
    },

    "presets": {
      "type": "array",
      "description": "Presets are default configurations of blocks that enable merchants to easily add a block to a JSON template through the theme editor.",
      "markdownDescription": "Presets are default configurations of blocks that enable merchants to easily add a block to a JSON template through the theme editor.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/blocks/theme-blocks/schema#presets)",
      "items": {
        "$ref": "./preset.json"
      }
    },

    "tag": {
      "description": "The HTML element that is used to wrap the rendered block. Accepts any string up to 50 characters. Can be used to render custom HTML elements. Use null to render without a wrapping element.",
      "markdownDescription": "The HTML element that is used to wrap the rendered block. Accepts any string up to 50 characters. Can be used to render custom HTML elements.\n\nUse `null` to render without a wrapping element.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/blocks/theme-blocks/schema#tag)",
      "oneOf": [
        {
          "description": "If you don't want to use a <div>, then you can specify which kind of HTML element to use.",
          "markdownDescription": "If you don't want to use a `<div>`, then you can specify which kind of HTML element to use.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/blocks/theme-blocks/schema#tag)",
          "type": "string",
          "maxLength": 50
        },
        {
          "description": "Used to render the block without a wrapping element.",
          "markdownDescription": "Used to render the block without a wrapping element.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/blocks/theme-blocks/schema#rendering-blocks-without-a-wrapper)",
          "type": "null"
        }
      ]
    },

    "class": {
      "type": "string",
      "description": "When Shopify renders a block, it's wrapped in an HTML element with the shopify-block class. You can append other classes by using the class attribute.",
      "markdownDescription": "When Shopify renders a block, it's wrapped in an HTML element with the `shopify-block` class. You can append other classes by using the class attribute.\n\n---\n\n[Shopify reference](https://shopify.dev/docs/themes/architecture/blocks/theme-blocks/schema#class)"
    }
  }
}

=== Shopify/theme-liquid-docs/tests/fixtures/theme-block-basics.json
{
  "name": "my block",
  "blocks": [{ "type": "@app" }, { "type": "@theme" }],
  "class": "my-class",
  "tag": "custom-element",
  "settings": [
    {
      "type": "header",
      "content": "header name",
      "info": "header info"
    },
    {
      "type": "number",
      "id": "number",
      "label": "my number"
    }
  ],
  "presets": [
    {
      "name": "preset name",
      "settings": {
        "number": 1
      },
      "blocks": [
        {
          "type": "thing",
          "settings": {
            "some-setting": "some-value"
          }
        }
      ]
    }
  ]
}

=== Shopify/theme-liquid-docs/tests/fixtures/theme-block-presets-as-hash.json
{
    "name": "my block",
    "blocks": [{ "type": "@app" }, { "type": "@theme" }],
    "class": "my-class",
    "tag": "custom-element",
    "settings": [
      {
        "type": "header",
        "content": "header name",
        "info": "header info"
      },
      {
        "type": "number",
        "id": "number",
        "label": "my number"
      }
    ],
    "presets": [
      {
        "name": "preset name",
        "settings": {
          "number": 1
        },
        "blocks": {
          "some-block-id": {
            "type": "button"
          },
          "some-other-block-id": {
            "type": "image",
            "static": true,
            "settings": {
              "some-setting": "some-value"
            }
          }
        }
      }
    ]
  }

=== Shopify/theme-liquid-docs/tests/fixtures/theme-block-2.json
{
  "name": "Group",
  "tag": null,
  "blocks": [{ "type": "@theme" }, { "type": "@app" }, { "type": "group" }],
  "settings": [
    {
      "type": "select",
      "id": "direction",
      "label": "Content direction",
      "options": [
        {
          "value": "row",
          "label": "Horizontal"
        },
        {
          "value": "column",
          "label": "Vertical"
        }
      ],
      "default": "row"
    },
    {
      "type": "select",
      "id": "justify_content",
      "label": "Content position",
      "options": [
        {
          "value": "flex-start",
          "label": "Start"
        },
        {
          "value": "center",
          "label": "Center"
        },
        {
          "value": "flex-end",
          "label": "End"
        }
      ],
      "default": "flex-start"
    },
    {
      "type": "color_scheme",
      "id": "color_scheme",
      "label": "Color scheme",
      "default": "scheme-1"
    },
    {
      "type": "range",
      "id": "width",
      "label": "Width",
      "min": 20,
      "max": 100,
      "step": 1,
      "unit": "%",
      "default": 100
    },
    {
      "type": "paragraph",
      "content": "Width is automatically optimized for mobile."
    },
    {
      "type": "range",
      "id": "padding",
      "label": "Padding",
      "min": 0,
      "max": 100,
      "step": 1,
      "unit": "px",
      "default": 16
    }
  ],
  "presets": [
    {
      "name": "Group"
    },
    {
      "name": "Column",
      "settings": {
        "direction": "column",
        "width": 25,
        "padding": 0
      },
      "blocks": [
        {
          "type": "image",
          "settings": {
            "ratio": "1"
          }
        },
        {
          "type": "group",
          "settings": {
            "padding": 0
          },
          "blocks": [
            {
              "type": "heading",
              "settings": {
                "heading": "Column",
                "heading_size": "h3"
              }
            },
            {
              "type": "text",
              "settings": {
                "text": "<p>Pair text with an image to focus on your chosen product, collection, or blog post. Add details on availability, style, or even provide a review.</p>"
              }
            }
          ]
        }
      ]
    },
    {
      "name": "Row",
      "settings": {
        "direction": "column"
      },
      "blocks": [
        {
          "type": "group",
          "settings": {
            "padding": 0
          },
          "blocks": [
            {
              "type": "image",
              "settings": {
                "width": 50
              }
            },
            {
              "type": "group",
              "settings": {
                "direction": "column",
                "width": 50,
                "padding": 60
              },
              "blocks": [
                {
                  "type": "text",
                  "settings": {
                    "text": "<p>Caption</p>",
                    "text_style": "text-block--caption"
                  }
                },
                {
                  "type": "heading",
                  "settings": {
                    "heading": "Row"
                  }
                },
                {
                  "type": "text",
                  "settings": {
                    "text": "<p>Share information about your brand with your customers. Describe a product, make announcements, or welcome customers to your store.</p>"
                  }
                },
                {
                  "type": "link",
                  "settings": {
                    "style_class": "button-secondary"
                  }
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "name": "Icon with text",
      "settings": {
        "justify_content": "center",
        "padding": 0
      },
      "blocks": [
        {
          "type": "group",
          "settings": {
            "direction": "column",
            "justify_content": "center",
            "width": 33,
            "padding": 0
          },
          "blocks": [
            {
              "type": "icon",
              "settings": {
                "icon": "dairy_free"
              }
            },
            {
              "type": "heading",
              "settings": {
                "heading_size": "h3",
                "alignment": "center"
              }
            }
          ]
        },
        {
          "type": "group",
          "settings": {
            "direction": "column",
            "justify_content": "center",
            "width": 33,
            "padding": 0
          },
          "blocks": [
            {
              "type": "icon",
              "settings": {
                "icon": "carrot"
              }
            },
            {
              "type": "heading",
              "settings": {
                "heading_size": "h3",
                "alignment": "center"
              }
            }
          ]
        },
        {
          "type": "group",
          "settings": {
            "direction": "column",
            "justify_content": "center",
            "width": 33,
            "padding": 0
          },
          "blocks": [
            {
              "type": "icon",
              "settings": {
                "icon": "nut_free"
              }
            },
            {
              "type": "heading",
              "settings": {
                "heading_size": "h3",
                "alignment": "center"
              }
            }
          ]
        }
      ]
    }
  ]
}

=== Shopify/theme-liquid-docs/tests/fixtures/theme-block-1.json
{
  "name": "Collapsible row",
  "tag": "details",
  "blocks": [{ "type": "@theme" }, { "type": "@app" }],
  "settings": [
    {
      "type": "text",
      "id": "summary",
      "label": "Heading",
      "default": "Collapsible row"
    },
    {
      "type": "select",
      "id": "icon",
      "label": "Icon",
      "options": [
        {
          "value": "none",
          "label": "None"
        },
        {
          "value": "apple",
          "label": "Apple"
        },
        {
          "value": "arrow",
          "label": "Arrow"
        },
        {
          "value": "banana",
          "label": "Banana"
        },
        {
          "value": "bottle",
          "label": "Bottle"
        },
        {
          "value": "box",
          "label": "Box"
        },
        {
          "value": "carrot",
          "label": "Carrot"
        },
        {
          "value": "chat_bubble",
          "label": "Chat bubble"
        },
        {
          "value": "check_mark",
          "label": "Check mark"
        },
        {
          "value": "clipboard",
          "label": "Clipboard"
        },
        {
          "value": "dairy",
          "label": "Dairy"
        },
        {
          "value": "dairy_free",
          "label": "Dairy free"
        },
        {
          "value": "dryer",
          "label": "Dryer"
        },
        {
          "value": "eye",
          "label": "Eye"
        },
        {
          "value": "facebook",
          "label": "Facebook"
        },
        {
          "value": "fire",
          "label": "Fire"
        },
        {
          "value": "gluten_free",
          "label": "Gluten free"
        },
        {
          "value": "heart",
          "label": "Heart"
        },
        {
          "value": "instagram",
          "label": "Instagram"
        },
        {
          "value": "iron",
          "label": "Iron"
        },
        {
          "value": "leaf",
          "label": "Leaf"
        },
        {
          "value": "leather",
          "label": "Leather"
        },
        {
          "value": "lightning_bolt",
          "label": "Lightning bolt"
        },
        {
          "value": "lipstick",
          "label": "Lipstick"
        },
        {
          "value": "lock",
          "label": "Lock"
        },
        {
          "value": "map_pin",
          "label": "Map pin"
        },
        {
          "value": "nut_free",
          "label": "Nut free"
        },
        {
          "value": "pants",
          "label": "Pants"
        },
        {
          "value": "paw_print",
          "label": "Paw print"
        },
        {
          "value": "pepper",
          "label": "Pepper"
        },
        {
          "value": "perfume",
          "label": "Perfume"
        },
        {
          "value": "pinterest",
          "label": "Pinterest"
        },
        {
          "value": "plane",
          "label": "Plane"
        },
        {
          "value": "plant",
          "label": "Plant"
        },
        {
          "value": "price_tag",
          "label": "Price tag"
        },
        {
          "value": "question_mark",
          "label": "Question mark"
        },
        {
          "value": "recycle",
          "label": "Recylce"
        },
        {
          "value": "return",
          "label": "Return"
        },
        {
          "value": "ruler",
          "label": "Ruler"
        },
        {
          "value": "serving_dish",
          "label": "Serving dish"
        },
        {
          "value": "shirt",
          "label": "Shirt"
        },
        {
          "value": "shoe",
          "label": "Shoe"
        },
        {
          "value": "silhouette",
          "label": "Silhouette"
        },
        {
          "value": "snapchat",
          "label": "Snapchat"
        },
        {
          "value": "snowflake",
          "label": "Snowflake"
        },
        {
          "value": "star",
          "label": "Star"
        },
        {
          "value": "stopwatch",
          "label": "Stopwatch"
        },
        {
          "value": "tiktok",
          "label": "Tiktok"
        },
        {
          "value": "truck",
          "label": "Truck"
        },
        {
          "value": "tumblr",
          "label": "Tumblr"
        },
        {
          "value": "twitter",
          "label": "X (Twitter)"
        },
        {
          "value": "vimeo",
          "label": "Vimeo"
        },
        {
          "value": "washing",
          "label": "Washing"
        }
      ],
      "default": "check_mark"
    }
  ],
  "presets": [{ "name": "Collapsible row" }]
}
